language: elixir
elixir:
  - 1.2.2
otp_release:
  - 18.2.1
services:
  - postgresql
before_script:
  - psql -c "CREATE USER dev WITH PASSWORD 'dev' CREATEDB;" -U postgres
  - mix ecto.create -r AuthService.Repo
  - mix ecto.migrate -r AuthService.Repo
